import stylisticJs from "@stylistic/eslint-plugin-js";
import stylisticJsx from "@stylistic/eslint-plugin-jsx";
import stylistic from "@stylistic/eslint-plugin";

export default [
    {
        "files": ["**/*.{js,jsx}"],
        "plugins": {
            "@stylistic/js": stylisticJs,
            "@stylistic/jsx": stylisticJsx,
            "@stylistic": stylistic,
        },
        "languageOptions": {
            "parserOptions": {
                "ecmaFeatures": {
                    "jsx": true,
                },
            },
        },
        "rules": {
            "semi": "error",
            "indent": ["error", 4],
            "quotes": ["error", "double"],
            "no-const-assign": "error",
            "no-dupe-class-members": "error",
            "no-dupe-else-if": "error",
            "no-dupe-keys": "error",
            "no-duplicate-case": "error",
            "no-duplicate-imports": ["error", { "includeExports": true }],
            "no-self-compare": "error",
            "no-unreachable": "error",
            "no-use-before-define": "error",
            "arrow-body-style": ["error", "always"],
            "block-scoped-var": "error",
            "curly": ["error", "all"],
            "default-param-last": "error",
            "no-redeclare": "error",
            "prefer-template": "error",
            "arrow-parens": ["error", "always"],
            "arrow-spacing": ["error", { "before": true, "after": true }],
            "@stylistic/block-spacing": ["error", "always"],
            "@stylistic/comma-dangle": ["error", "always-multiline"],
            "comma-spacing": ["error", { "before": false, "after": true }],
            "comma-style": ["error", "last"],
            "eol-last": ["error", "always"],
            "@stylistic/js/function-call-spacing": ["error", "never"],
            "@stylistic/jsx/jsx-equals-spacing": [2, "always"],
            "@stylistic/jsx/jsx-props-no-multi-spaces": "error",
            "@stylistic/jsx-quotes": ["error", "prefer-double"],
            "@stylistic/js/key-spacing": ["error", { "beforeColon": false, "afterColon": true }],
            "@stylistic/jsx-equals-spacing": ["error", "always"],
            "@stylistic/jsx/jsx-curly-spacing": ["error", "never"],
            "@stylistic/jsx/jsx-tag-spacing": ["error", { "closingSlash": "never", "beforeSelfClosing": "never", "afterOpening": "never", "beforeClosing": "never" }],
            "@stylistic/jsx/jsx-first-prop-new-line": ["error", "never"],
            "@stylistic/jsx/jsx-indent": ["error", 4],
            "@stylistic/jsx-self-closing-comp": "error",
            "@stylistic/jsx-props-no-multi-spaces": "error",
            "@stylistic/jsx/jsx-self-closing-comp": ["error", { "component": true, "html": true }],
            "@stylistic/jsx/jsx-wrap-multilines": ["error", { "declaration": "parens-new-line", "assignment": "parens-new-line", "return": "parens-new-line", "arrow": "parens-new-line", "condition": "parens-new-line", "logical": "parens-new-line", "prop": "parens-new-line" }],
            "no-extra-semi": "error",
            "no-floating-decimal": "error",
            "no-mixed-operators": "error",
            "no-mixed-spaces-and-tabs": "error",
            "no-multi-spaces": "error",
            "no-tabs": ["error", { "allowIndentationTabs": false }],
            "no-whitespace-before-property": "error",
            "object-curly-spacing": ["error", "always"],
            "@stylistic/js/one-var-declaration-per-line": ["error", "initializations"],
            "operator-linebreak": ["error", "none"],
            "quote-props": ["error", "always"],
            "semi-spacing": ["error"],
            "semi-style": ["error", "last"],
            "space-before-blocks": "error",
            "space-in-parens": ["error", "never"],
            "space-infix-ops": "error",
            "@stylistic/js/spaced-comment": ["error", "always"],
            "@stylistic/js/switch-colon-spacing": ["error", { "after": true, "before": false }],
            "template-curly-spacing": "error",
            "wrap-regex": "error",
        },
        "ignores": ["tailwind.config.js"],
    },
];
